rule create_autosomal_qc_set:
    input:
        # Genotype dataset after sample missingness filtering.
        bed=rules.apply_sample_missingness.output.bed,
        bim=rules.apply_sample_missingness.output.bim,
        fam=rules.apply_sample_missingness.output.fam,
    output:
        # Autosomal dataset filtered for MAF, variant missingness,
        # and Hardy-Weinberg equilibrium.
        bed=ws_path(
            "heterozygosity/autosomal_qc.bed"
        ),
        bim=ws_path(
            "heterozygosity/autosomal_qc.bim"
        ),
        fam=ws_path(
            "heterozygosity/autosomal_qc.fam"
        ),
        log=ws_path(
            "heterozygosity/autosomal_qc.log"
        ),
    container:
        "docker://gitlab.fht.org:5050/hds-center/containers/plink2:0e8e82d8"
    threads:
        8
    resources:
        runtime=120,
        mem_mb=16000,
    params:
        # Input PLINK prefix.
        bfile=ws_path(
            "sample_missingness/genotype"
        ),

        # Output PLINK prefix.
        prefix=ws_path(
            "heterozygosity/autosomal_qc"
        ),

        # Minimum minor allele frequency.
        maf=config["thresholds"]["maf"],

        # Maximum allowed variant missingness.
        geno=config["thresholds"]["variant_missingness"],

        # Hardy-Weinberg equilibrium p-value threshold.
        hwe=config["thresholds"]["hwe"],
    shell:
        r"""
        set -euo pipefail

        mkdir -p "$(dirname "{output.bed}")"

        plink2 \
            --bfile "{params.bfile}" \
            --autosome \
            --maf "{params.maf}" \
            --geno "{params.geno}" \
            --hwe "{params.hwe}" \
            --make-bed \
            --out "{params.prefix}" \
            --threads {threads} \
            --memory {resources.mem_mb}
        """


rule compute_heterozygosity:
    input:
        # Autosomal QC dataset.
        bed=rules.create_autosomal_qc_set.output.bed,
        bim=rules.create_autosomal_qc_set.output.bim,
        fam=rules.create_autosomal_qc_set.output.fam,
    output:
        # Per-sample heterozygosity statistics generated by PLINK.
        het=ws_path(
            "heterozygosity/heterozygosity.het"
        ),

        # PLINK execution log.
        log=ws_path(
            "heterozygosity/heterozygosity.log"
        ),
    container:
        "docker://gitlab.fht.org:5050/hds-center/containers/plink2:0e8e82d8"
    threads:
        8
    resources:
        runtime=90,
        mem_mb=8000,
    params:
        bfile=ws_path(
            "heterozygosity/autosomal_qc"
        ),
        prefix=ws_path(
            "heterozygosity/heterozygosity"
        ),
    shell:
        r"""
        set -euo pipefail

        mkdir -p "$(dirname "{output.het}")"

        plink2 \
            --bfile "{params.bfile}" \
            --het \
            --out "{params.prefix}" \
            --threads {threads} \
            --memory {resources.mem_mb}
        """


rule heterozygosity_qc:
    input:
        # PLINK heterozygosity report.
        het=rules.compute_heterozygosity.output.het,
    output:
        # Distribution of the heterozygosity statistic.
        plot=ws_path(
            "heterozygosity/heterozygosity.png"
        ),

        # PLINK-compatible list of suggested sample exclusions.
        exclusions=ws_path(
            "heterozygosity/heterozygosity_exclusions.tsv"
        ),

        # Heterozygosity statistics and QC status for all samples.
        table=ws_path(
            "heterozygosity/heterozygosity_all_samples.tsv"
        ),

        # Summary of the heterozygosity QC step.
        summary=ws_path(
            "heterozygosity/heterozygosity.summary.tsv"
        ),
    conda:
        "../envs/r_environment.yaml"
    resources:
        runtime=30,
        mem_mb=4096,
    params:
        # Samples outside mean ± n_sd standard deviations
        # will be suggested for exclusion.
        n_sd=config["thresholds"]["heterozygosity_sd"],
    shell:
        r"""
        set -euo pipefail

        mkdir -p "$(dirname "{output.plot}")"

        Rscript workflow/scripts/heterozygosity_qc.R \
            --het "{input.het}" \
            --n-sd "{params.n_sd}" \
            --plot "{output.plot}" \
            --suggested-exclusions "{output.exclusions}" \
            --table "{output.table}" \
            --summary "{output.summary}"
        """

